### ISSUE TITLE
Unable to download model weights

### ISSUE THREAD

**Issue by ling-zzZ** [QLYoo/Portraitmatting#1]
I'm glad you shared your work, but I can't seem to download the model weights you shared.

**Comment by Windaway** [comment]
这个模型可能需要在宽松的网络条件下下载……

**Comment by ling-zzZ** [comment]
能否同步放在百度云盘上面呢

**Comment by Windaway** [comment]
链接：https://pan.baidu.com/s/1VUsM42y1YWRZWY1uXlRAnw?pwd=ku4v 
提取码：ku4v
